# Generated by Django 5.1.6 on 2025-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='member_type',
            field=models.CharField(choices=[('PROF', 'Professor'), ('RA', 'Research Assistant'), ('ASSOC', 'Research Associate'), ('MASTERS', 'Masters Student'), ('PHD', 'PhD Researcher'), ('POSTDOC', 'Postdoctoral Fellow'), ('SOFTWARE_ENG', 'Software Engineer'), ('STAFF', 'Staff'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
