# Generated by Django 5.1.6 on 2025-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_content', '0002_alter_labmember_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='google_scholar_id',
            field=models.CharField(blank=True, help_text='User ID from Google Scholar URL', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='external_id',
            field=models.CharField(blank=True, help_text='Unique ID from external API (e.g. SerpApi id)', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Raw API response for debugging', null=True),
        ),
    ]
